import Head from "next/head";
import Image from "next/image";
import Tip from "../components/Tip";

export default function Home() {
  return (
    <div className="h-screen w-full">
      <Head>
        <title>Splitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main className="h-full w-ful">
        <Tip />
      </main>
    </div>
  );
}
